name: EC2 Deployment on Release

on:
  release:
    types: [created]

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI using AWS credentials from GitHub Secrets
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-west-1"

      # Step 3: Run the EC2 deployment script with parameters
      - name: Run EC2 deployment script
        run: |
          chmod +x ./scripts/spawn.sh
          ./scripts/spawn.sh "${{ secrets.INSTANCE_ID }}" "backup" "release" "${{ secrets.TARGET_GROUP_ARN }}"
